import type { Metadata } from "next";
import Head from "next/head";
import { Oswald, Funnel_Sans } from 'next/font/google';

import config from '../../next.config';

import "./globals.css";

const oswald = Oswald({
  subsets: ['latin'],
  variable: "--font-oswald",
  display: 'swap',
});

const funnelSans = Funnel_Sans({
  subsets: ['latin'],
  variable: "--font-funnel-sans",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <base href={config.basePath} />
      </Head>
      <body
        className={`${funnelSans.variable} ${oswald.variable} antialiased`}
      >
        <div className="body-container">
          {children}
        </div>
      </body>
    </html>
  );
}
