import type { Metadata } from "next";
import { Suspense } from "react";
import { Oswald, Funnel_Sans } from 'next/font/google';

import Loading from './loading';
import "./globals.css";

const oswald = Oswald({
  subsets: ['latin'],
  variable: "--font-oswald",
  display: 'swap',
});

const funnelSans = Funnel_Sans({
  subsets: ['latin'],
  variable: "--font-funnel-sans",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading />}>
        <body
          className={`${funnelSans.variable} ${oswald.variable} antialiased`}
        >
          <div className="body-container">
            {children}
          </div>
        </body>
      </Suspense>
    </html>
  );
}
